version: '3.8'

#-----------------create network-----------------------
networks:
  mm-net:
    name: mm-net
    driver: bridge

services:
#-----------------mattermost host 1-----------------------
  mm-1:
    image: mattermost/mattermost-preview
    networks:
      - mm-net
    ports:
      - 8065:8065
#-----------------mattermost host 2-----------------------
  mm-2:
    image: mattermost/mattermost-preview
    networks:
      - mm-net
    ports:
      - 8066:8065
    depends_on:
      - mm-1
#-----------------mattermost host 3-----------------------
  mm-3:
    image: mattermost/mattermost-preview
    networks:
      - mm-net
    ports:
      - 8067:8065
    depends_on:
      - mm-2
#-----------------matterbridge-----------------------
  mb:
    image: 42wim/matterbridge
    networks:
      - mm-net
#    network_mode: host
    volumes:
      - type: bind
        source: ./matterbridge
        target: /etc/matterbridge
    depends_on:
      - mm-3

#    entrypoint: /bin/sh -c "sleep 30000"